### ISSUE TITLE
Attempting to manually map ntdll.dll leads to a FileNotFoundException in RewriteModuleIAT

### ISSUE THREAD

**Issue by NotoriousRebel** [cobbr/SharpSploit#57] opened 2020-08-04 22:15 UTC
```csharp

Console.WriteLine("[?] Manually map a fresh copy of a DLL (\"ntdll.dll\"), and resolve a function by walking the export table in-memory...");
SharpSploit.Execution.PE.PE_MANUAL_MAP moduleDetails = SharpSploit.Execution.ManualMap.Map.MapModuleToMemory("C:\\Windows\\System32\\ntdll.dll");
Console.WriteLine("[>] Module Base : " + string.Format("{0:X}", moduleDetails.ModuleBase.ToInt64()) + "\n");

```

Traceback:

```
Unhandled Exception: System.IO.FileNotFoundException: IIIIIIIIIIIIIIIII?9L<Éu:·IE3Of.Éx4H.OA<AHEAI%,_ÿ, unable to find the specified file.
   at SharpSploit.Execution.ManualMap.Map.RewriteModuleIAT(PE_META_DATA PEINFO, IntPtr ModuleMemoryBase)
   at SharpSploit.Execution.ManualMap.Map.MapModuleToMemory(IntPtr pModule, IntPtr pImage, PE_META_DATA PEINFO)
   at SharpSploit.Execution.ManualMap.Map.MapModuleToMemory(IntPtr pModule)
   at BaseLibraryMapper.Program.Main(String[] args) in D:\repos\BaseLibraryMapper\Program.cs:line 16
```

**Comment by Dewera** [comment] 2020-08-04 23:02
The issue here comes from the fact that `ntdll.dll` has no import directory. The current implementation always assumes there is a valid import directory as seen [here](https://github.com/cobbr/SharpSploit/blob/0ce3a87dc4726afc78d595550d49feda5b2b2c63/SharpSploit/Execution/ManualMap/Map.cs#L193)

Something like the following should provide fix

```csharp

if (idd.VirtualAddress == 0)
{
    return;
}

IntPtr pImportTable = (IntPtr)((UInt64)ModuleMemoryBase + idd.VirtualAddress);
```

**Comment by TheWover** [comment] 2020-08-05 02:04
Thanks @Dewera ! I'll look into this an add handling for this edge case.

BTW, I realized that this is a duplicate of this other Issue by rastamouse: https://github.com/cobbr/SharpSploit/issues/55

**Closed** 2020-10-03 23:25 UTC
Labels: duplicate
